const permissons = {
  ORDER_CREATE: 'ORDER_CREATE',
  ORDER_PACKAGING: 'ORDER_PACKAGING',
  ORDER_DISTRIBUTING: 'ORDER_DISTRIBUTING',
  ORDER_TRANSPORTING: 'ORDER_TRANSPORTING',
  CLIENT_CREATE: 'CLIENT_CREATE'
}

module.exports = permissons
